<a href="https://colab.research.google.com/github/Ekawaka/PYTHON-DATA-ANALYSIS/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# 1. Import the numpy package under the name np
import numpy as np

In [ ]:
# 2. Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

In [ ]:
# 3. Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)

In [ ]:
# 4. How to find the memory size of any array
arr = np.zeros((3,2))
# an example of array of shape (3,2) filled with zeros
# using the nbytes attribute
memory_size = arr.nbytes
print("memory_size:", memory_size, "bytes")

In [ ]:
# 5. How to get the documentation of the numpy add function from the command line?
help(np.add)

In [ ]:
# 6. Create a null vector of size 10 but the fifth value which is 1
# create a null vector of size 10
null_vector = np.zeros(10)
#assign the 5th value (index 4)to be 1
null_vector[4] = 1
print(null_vector)

In [ ]:
# 7.Create a vector with values ranging from 10 to 49
vector = np.arange(10,50)
print(vector)

In [ ]:
# 8. Reverse a vector (first element becomes last)
vector = np.arange(10,50)
# reverse the vector
reversed_vector = vector[::-1]
print(reversed_vector)


In [ ]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
vector = np.arange(9)
#reshape the vector a 3x3 matrix
matrix = vector.reshape(3,3)
print(matrix)

In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
# create a list
my_list = [1,2,0,0,4,0]
# convert the list to a numpy array
arr = np. array(my_list)
# find the indices of non zero elements
indices = np.nonzero(arr)
print(indices)

In [ ]:
# 11. Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print(identity_matrix)

In [ ]:
# 12. Create a 3x3x3 array with random values
# random values between 0 and 1
random_array = np.random.rand(3,3,3)
print(random_array)
# random values between 0 and 10
random_array = np.random.rand(3,3,3)*10
print(random_array)

In [ ]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
random_array = np.random.rand(10,10)
# find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()
print(min_value)
print(max_value)

In [ ]:
# 14. Create a random vector of size 30 and find the mean value
random_vector = np.random.rand(30)
print(random_vector)
# find the mean value.
mean_value = np.mean(random_vector)
print(mean_value)

In [43]:
# 15. Create a 2d array with 1 on the border and 0 inside
# define the shape of 2D array
rows, columns = 4,4
# create an array filled with zeros
array_2d = np.zeros((rows, columns))
# assign 1 to the border elements
array_2d[0, :] = 1 # top row
array_2d[-1, :] = 1
array_2d[:, 0] = 1 # left column
array_2d[:, -1] = 1
print(array_2d)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
