<a href="https://colab.research.google.com/github/Ekawaka/PYTHON-DATA-ANALYSIS/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np

In [ ]:
# 16. How to add a border (filled with 0's) around an existing array?
existing_array = np.array([[9,8,7],
                          [6,5,4],
                          [3,2,1]])
# Get shape of the existing array
rows, columns = existing_array.shape
# Define the size od the new array with border
new_rows = rows + 2
new_columns = columns + 2
# create a new array filled with zeros
new_array = np.zeros((new_rows, new_columns))
# copy the existing array into the centre of the new array
existing_array = new_array[1:-1, 1:-1]
print(existing_array)
print(new_array)



In [7]:
# 17.  What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [8]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5,5))
# set values 1,2,3 and 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1,2,3,4])
print(matrix)



[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [9]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
# Create a 8x8 matrix and filled with zeros
matrix = np.zeros((8,8), dtype=int)

# Fill the matrix with checkerboard pattern
matrix[::2, ::2] = 1 # fill even rows and even columns with 1
matrix[1::2, 1::2] = 1 # fill odd rows and odd columns with 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [11]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

# Define the shape of array
shape = (6,7,8)

# Calculate the flat index of the 100th element
flat_index = 100-1 # since indexing starts from 0, we then substract 1

# Determine the indices (x,y,z) from flat index
x_index = flat_index // (shape[1] * shape[2])
yz_remainder = flat_index % (shape[1] * shape[2])
y_index = yz_remainder // shape[2]
z_index = yz_remainder % shape[2]

print("Index(x,y,z) of the 100th element", (x_index, y_index, z_index))

Index(x,y,z) of the 100th element (1, 5, 3)


In [13]:
# 21. Create a checkerboard 8x8 matrix using the tile function

# Define 2x2 checkerboard pattern
checkerboard_pattern = np.array([[0,1],[1,0]])

# using tile function to create an 8x8 checkerboard matrix
checkerboard_8x8 = np.tile(checkerboard_pattern, (4,4))
print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# 22. Normalize a 5x5 random matrix
# Create a 5x5 random matrix
random_matrix = np.random.rand(5,5)

# Normolize the matrix to the range [0,1]
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())

# Normolize the matrix using z_score normalization
z_score_normalized_matrix = (random_matrix - random_matrix.mean()) / (random_matrix.std())

print(normalized_matrix)
print(z_score_normalized_matrix)


[[-0.46827972  0.29192281 -0.09238754 -0.82264392  1.4007917 ]
 [ 0.7022819  -0.20943794 -1.07497831  0.51353166 -0.78041248]
 [-0.99298146 -1.17386203  0.07957659 -0.51070681  1.71025429]
 [-0.16880667  1.99960707  1.85521946 -0.95088278 -0.57067075]
 [ 1.54725848 -0.75804068 -1.05382962  0.48383334 -0.95635661]]


In [18]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

# Define custom dtype for RGBA color
rgba_dtype = np.dtype([('R', np.uint8),
                       ('G', np.uint8),
                       ('B', np.uint8),
                       ('A', np.uint8)])
# example RGBA color
color = np.array((234, 126, 56, 234), dtype=rgba_dtype)

print("RGBA color:", color)

RGBA color: (234, 126, 56, 234)


In [19]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

# Create a 5x3 matrix
matrix_a = np.random.rand(5,3)

# Create a 3x2 matrix
matrix_b = np.random.rand(3,2)

# Multiplication
result = np.dot(matrix_a, matrix_b)

print(result)


[[1.11536861 0.58747301]
 [1.36131879 1.20762851]
 [0.96865858 0.75933482]
 [1.27249724 0.90463821]
 [2.30379917 1.68791552]]


In [31]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
# Create a 1D array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Negate elements between 3 and 8 (inclusive) in place
arr[(arr >= 3) & (arr <= 8)] *= -1

print = ("Result:", arr)



In [37]:
# 26. What is the output of the following script?
# Author: Jake VanderPlas
from numpy import *
#'print(sum(range(5), -1))':

#'print(sum(range(5), -1))':


In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
# 28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [48]:
# 29. How to round away from zero a float array ?
# Float array
float_array = np.array([-3.5, -2.7, -1.8, -0.9, 0.9, 1.8, 2.7, 3.5])

# Round away from zero
rounded_array = np.where(float_array >= 0, np.ceil(float_array), np.floor(float_array))
print(rounded_array)

TypeError: 'tuple' object is not callable

In [50]:
# 30. How to find common values between two arrays?

# Define two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print(common_values)

TypeError: 'tuple' object is not callable