<a href="https://colab.research.google.com/github/Ekawaka/PYTHON-DATA-ANALYSIS/blob/main/numpyweeklyproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
# 61. Find the nearest value from a given value in an array

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.array([1, 2, 3, 4, 5])
value = 4.5

nearest_value = find_nearest(array, value)
print("Nearest value to", value, "in the array is:", nearest_value)

In [ ]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

# Define the two arrays
array1 = np.array([[1, 2, 3]])  # Shape: (1,3)
array2 = np.array([[4], [5], [6]])  # Shape: (3,1)

# Initialize the sum
sum_result = 0

# Iterate over the arrays and compute the sum
for x, y in zip(array1.flat, array2.flat):
    sum_result += x + y

print("Sum of the two arrays:", sum_result)

In [5]:
# 63. Create an array class that has a name attribute

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

data = [1, 2, 3, 4, 5]
name = "Example Array"

# Create a NamedArray instance
arr = NamedArray(data, name=name)

# Access the array and its name attribute
print("Array:", arr)
print("Name:", arr.name)

Array: [1 2 3 4 5]
Name: Example Array


In [ ]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

def add_one_to_indices(vector, indices):
    # Get unique indices to avoid adding 1 multiple times to the same index
    unique_indices = np.unique(indices)

    # Create a new array with the same shape as the given vector
    result = np.copy(vector)

    # Increment elements at the specified indices by 1
    result[unique_indices] += 1

    return result

# Example usage:
vector = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 1, 2, 2, 3, 3, 4])

result = add_one_to_indices(vector, indices)
print("Result:", result)

In [ ]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

def accumulate_elements(X, I, F):
    # Ensure that F has the same shape as the accumulated array
    F = np.zeros_like(F)

    # Accumulate elements of X into F based on index list I
    np.add.at(F, I, X)

    return F

# Example usage:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 1, 2, 3])
F = np.zeros(4)

result = accumulate_elements(X, I, F)
print("Result:", result)

In [ ]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

def compute_unique_colors(image):
    # Reshape the image to a 2D array where each row represents a pixel
    flattened_image = image.reshape(-1, 3)

    # Compute the unique colors
    unique_colors = np.unique(flattened_image, axis=0)

    # Return the number of unique colors
    return len(unique_colors)

# Example usage:
# Create a sample image (replace this with your image data)
w, h = 10, 10
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.ubyte)

# Compute the number of unique colors
num_unique_colors = compute_unique_colors(image)
print("Number of unique colors:", num_unique_colors)

In [ ]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?

# Create a sample four-dimensional array (replace this with your array data)
arr = np.random.randint(0, 10, size=(3, 4, 2, 2))

# Get the sum over the last two axes at once
sum_last_two_axes = np.sum(arr, axis=(-2, -1))

print("Original array:")
print(arr)
print("\nSum over the last two axes:")
print(sum_last_two_axes)

In [10]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

def compute_subset_means(D, S):
    # Get unique subset indices
    unique_indices = np.unique(S)

    # Initialize an array to store the means of subsets
    subset_means = np.zeros(len(unique_indices))

    # Compute the mean for each subset
    for i, idx in enumerate(unique_indices):
        subset = D[S == idx]  # Select elements of D corresponding to the current subset index
        subset_means[i] = np.mean(subset)

    return subset_means

# Example usage:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 1, 0, 1, 2, 2, 3, 3, 3, 3])

subset_means = compute_subset_means(D, S)
print("Subset means:", subset_means)

Subset means: [2.  3.  5.5 8.5]


In [11]:
# 69. How to get the diagonal of a dot product?

def diagonal_of_dot_product(A, B):
    # Compute the dot product of matrices A and B
    dot_product = np.einsum('ij,jk->ik', A, B)

    # Get the diagonal elements
    diagonal = np.diag(dot_product)

    return diagonal

# Example usage:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[2, 0],
              [1, 3],
              [4, 2]])

diagonal = diagonal_of_dot_product(A, B)
print("Diagonal of the dot product:", diagonal)

Diagonal of the dot product: [16 27]


In [12]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Number of consecutive zeros
num_zeros = 3

# Build new vector with interleaved zeros
new_vector = np.zeros(len(original_vector) + (len(original_vector) - 1) * num_zeros, dtype=original_vector.dtype)
new_vector[::num_zeros+1] = original_vector

print("New vector with interleaved zeros:")
print(new_vector)

New vector with interleaved zeros:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [13]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

# Create arrays
array_3d = np.random.rand(5, 5, 3)  # Dimension (5,5,3)
array_2d = np.random.rand(5, 5)      # Dimension (5,5)

# Multiply array_3d by array_2d
result = array_3d * array_2d[:, :, np.newaxis]

print("Resulting array shape:", result.shape)

Resulting array shape: (5, 5, 3)


In [ ]:
# 72. How to swap two rows of an array?
# Create a sample array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 0 and 1
array[[0, 1]] = array[[1, 0]]

print("Array after swapping rows 0 and 1:")
print(array)

In [ ]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

# Define a function to extract line segments from a triangle
def extract_segments(triangle):
    segments = set()
    for i in range(3):
        for j in range(i+1, 3):
            segments.add(tuple(sorted((triangle[i], triangle[j]))))
    return segments

# Define the set of triplets describing 10 triangles
triplets = [(1, 2, 3), (2, 3, 4), (3, 4, 5), (4, 5, 6), (5, 6, 7),
            (6, 7, 8), (7, 8, 9), (8, 9, 10), (9, 10, 11), (10, 11, 12)]

# Initialize an empty set to store unique line segments
unique_segments = set()

# Iterate over each triplet and extract line segments
for triplet in triplets:
    segments = extract_segments(triplet)
    unique_segments.update(segments)

print("Set of unique line segments:")
print(unique_segments)

In [ ]:
# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

def reconstruct_array(C):
    max_value = len(C) - 1  # Maximum value in array A
    A = np.repeat(np.arange(max_value + 1), C)
    return A

# Example usage:
C = np.array([0, 2, 1, 1, 0, 1, 0, 0, 2])  # Example sorted bincount array

A = reconstruct_array(C)
print("Array A:", A)
print("Bincount of A:", np.bincount(A))
print("Is np.bincount(A) == C?", np.array_equal(np.bincount(A), C))

In [ ]:
# 75. How to compute averages using a sliding window over an array?

def sliding_window_average(arr, window_size):
    # Define the window
    window = np.ones(window_size) / window_size

    # Compute the sliding window average using convolution
    averages = np.convolve(arr, window, mode='valid')

    return averages

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3

averages = sliding_window_average(arr, window_size)
print("Sliding window averages:", averages)

In [ ]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

def build_shifted_array(Z):
    # Create indices for slicing the array
    indices = np.arange(3)[:, np.newaxis] + np.arange(len(Z) - 2)

    # Use array slicing to build the shifted array
    shifted_array = Z[indices]

    return shifted_array

# Example usage:
Z = np.array([1, 2, 3, 4, 5, 6, 7])

result = build_shifted_array(Z)
print("Result:")
print(result)

In [ ]:
# 77. How to negate a boolean, or to change the sign of a float inplace?

# Original boolean value
boolean_value = True

# Negate the boolean in-place
boolean_value = ~boolean_value

print("Negated boolean value:", boolean_value)

# Original float value
float_value = 3.14

# Change the sign of the float in-place
float_value *= -1

print("Float value with changed sign:", float_value)

In [ ]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

def distance_to_lines(P0, P1, p):
    # Convert points to numpy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    p = np.array(p)

    # Compute direction vectors of the line segments
    v = P1 - P0

    # Compute vectors from P0 to p
    w = p - P0

    # Compute projection of w onto v
    c = np.dot(w, v) / np.dot(v, v)

    # Handle cases where c is outside [0, 1]
    c = np.clip(c, 0, 1)

    # Compute projected points
    projected_points = P0 + c[:, np.newaxis] * v

    # Compute distances between p and projected points
    distances = np.linalg.norm(projected_points - p, axis=1)

    return distances

# Example usage:
P0 = [(1, 1), (2, 3), (4, 5)]  # Endpoint 1 of line segments
P1 = [(4, 5), (6, 7), (8, 9)]  # Endpoint 2 of line segments
p = (3, 4)                     # Point p

distances = distance_to_lines(P0, P1, p)
print("Distances to each line segment:", distances)

In [ ]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

def distance_to_lines(P0, P1, P):
    # Convert points to numpy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    P = np.array(P)

    # Compute direction vectors of the line segments
    v = P1 - P0

    # Compute vectors from P0 to each point in P
    w = P[:, np.newaxis, :] - P0

    # Compute projection of w onto v
    c = np.einsum('ijk,ik->ij', w, v) / np.linalg.norm(v, axis=1)**2

    # Handle cases where c is outside [0, 1]
    c = np.clip(c, 0, 1)

    # Compute projected points
    projected_points = P0 + c[:, :, np.newaxis] * v

    # Compute distances between each point and its projected points
    distances = np.linalg.norm(projected_points - P[:, np.newaxis, :], axis=2)

    return distances

# Example usage:
P0 = [(1, 1), (2, 3), (4, 5)]  # Endpoint 1 of line segments
P1 = [(4, 5), (6, 7), (8, 9)]  # Endpoint 2 of line segments
P = [(3, 4), (5, 6)]            # Set of points P

distances = distance_to_lines(P0, P1, P)
print("Distances from each point to each line segment:")
print(distances)

In [25]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

def extract_subpart(arr, center, shape, fill_value=0):
    """
    Extracts a subpart from the input array centered on a given element
    with the specified shape, padding with a fill value when necessary.

    Parameters:
        arr (ndarray): Input array.
        center (tuple or list): Coordinates of the center element.
        shape (tuple or list): Shape of the subpart.
        fill_value (scalar, optional): Value to use for padding. Default is 0.

    Returns:
        ndarray: Extracted subpart with the specified shape.
    """
    # Convert center and shape to tuples if not already
    center = tuple(center)
    shape = tuple(shape)

    # Calculate start and end indices for each axis
    start_indices = tuple(c - s // 2 for c, s in zip(center, shape))
    end_indices = tuple(start + s for start, s in zip(start_indices, shape))

    # Pad array if necessary
    padded_arr = np.pad(arr, [(max(-start, 0), max(end - arr_size, 0)) for start, end, arr_size in zip(start_indices, end_indices, arr.shape)], constant_values=fill_value)

    # Calculate new start and end indices after padding
    new_start_indices = tuple(max(start, 0) for start in start_indices)
    new_end_indices = tuple(start + s for start, s in zip(new_start_indices, shape))

    # Extract subpart from padded array
    subpart = padded_arr[new_start_indices[0]:new_end_indices[0], new_start_indices[1]:new_end_indices[1]]

    return subpart

# Example usage:
arr = np.random.randint(0, 10, (10, 10))  # Example input array
center = (5, 5)                           # Center element coordinates
shape = (3, 3)                            # Shape of the subpart

subpart = extract_subpart(arr, center, shape, fill_value=-1)
print("Extracted subpart:")
print(subpart)

Extracted subpart:
[[5 7 3]
 [8 1 7]
 [2 5 1]]


In [ ]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Define the window size
window_size = 4

# Calculate the number of rows in R
num_rows = len(Z) - window_size + 1

# Generate the array R using array slicing
R = np.array([Z[i:i+window_size] for i in range(num_rows)])

print("Array R:")
print(R)

In [ ]:
# 82. Compute a matrix rank
# Define the matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)

In [ ]:
# 83. How to find the most frequent value in an array?

# Example array
array = np.array([1, 2, 3, 4, 2, 2, 3, 1, 4, 4, 4])

# Find the most frequent value
most_frequent_value = np.argmax(np.bincount(array))

print("Most frequent value:", most_frequent_value)

In [ ]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
# Create a random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))

# Extract all contiguous 3x3 blocks
blocks = [matrix[i:i+3, j:j+3] for i in range(8) for j in range(8)]

# Print the extracted blocks
for idx, block in enumerate(blocks, 1):
    print(f"Block {idx}:")
    print(block)
    print()

In [ ]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class SymmetricArray(np.ndarray):
    def __setitem__(self, key, value):
        i, j = key
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

# Create a 3x3 SymmetricArray subclass
Z = np.zeros((3, 3))
Z = Z.view(SymmetricArray)

# Assign values to the array
Z[0, 1] = 1
Z[1, 2] = 2

print("Symmetric Array Z:")
print(Z)


In [3]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

def sum_of_matrix_products(matrices, vectors):
    # Assuming matrices is a list of p matrices with shape (n, n)
    # Assuming vectors is a list of p vectors with shape (n, 1)
    # Convert lists to numpy arrays
    matrices = np.array(matrices)
    vectors = np.array(vectors)

    # Ensure matrices and vectors have compatible shapes
    assert matrices.shape[0] == vectors.shape[0], "Number of matrices and vectors should be the same"
    p = matrices.shape[0]

    # Compute the sum of matrix products
    result = np.sum(np.matmul(matrices, vectors), axis=0)

    return result

# Example usage
n = 3  # dimension of matrices and vectors
p = 5  # number of matrices and vectors

# Generating random matrices and vectors for demonstration
matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]

result = sum_of_matrix_products(matrices, vectors)
print(result)

[[3.90050972]
 [3.95528078]
 [4.47128308]]


In [ ]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

# Create a random 16x16 array for demonstration
array_16x16 = np.random.randint(1, 10, size=(16, 16))

# Reshape the array to make it a 4D array with shape (4, 4, 4, 4)
# This will split the 16x16 array into 4x4 blocks
blocks = array_16x16.reshape(4, 4, 4, 4)

# Sum along the last two axes to get the block-sum
block_sum = np.sum(blocks, axis=(2, 3))

print("Original 16x16 array:")
print(array_16x16)
print("\nBlock-sum (block size 4x4):")
print(block_sum)

In [ ]:
# 88. How to implement the Game of Life using numpy arrays?

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def update(frameNum, img, grid, N):
    newGrid = grid.copy()
    for i in range(N):
        for j in range(N):
            # Compute the sum of the eight neighbors
            total = int((grid[i, (j-1)%N] + grid[i, (j+1)%N] +
                         grid[(i-1)%N, j] + grid[(i+1)%N, j] +
                         grid[(i-1)%N, (j-1)%N] + grid[(i-1)%N, (j+1)%N] +
                         grid[(i+1)%N, (j-1)%N] + grid[(i+1)%N, (j+1)%N])/255)

            # Apply Conway's rules
            if grid[i, j] == ON:
                if (total < 2) or (total > 3):
                    newGrid[i, j] = OFF
            else:
                if total == 3:
                    newGrid[i, j] = ON

    img.set_data(newGrid)
    grid[:] = newGrid[:]
    return img

# Define constants
ON = 255
OFF = 0
N = 100
updateInterval = 50

# Create a random grid
grid = np.random.choice([ON, OFF], N*N, p=[0.2, 0.8]).reshape(N, N)

# Set up the animation
fig, ax = plt.subplots()
img = ax.imshow(grid, interpolation='nearest')
ani = animation.FuncAnimation(fig, update, fargs=(img, grid, N),
                              frames=10,
                              interval=updateInterval,
                              save_count=50)

plt.show()

In [ ]:
# 89. How to get the n largest values of an array

def n_largest(arr, n):
    indices = np.argpartition(arr, -n)[-n:]
    return indices[np.argsort(arr[indices])][::-1]

# Example array
arr = np.array([1, 6, 3, 8, 5, 2, 7, 4])
n = 3  # Number of largest values to find

# Get the indices of the n largest values
largest_indices = n_largest(arr, n)

# Get the n largest values themselves
largest_values = arr[largest_indices]

print("Indices of the {} largest values: {}".format(n, largest_indices))
print("The {} largest values: {}".format(n, largest_values))

In [ ]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

from itertools import product

def cartesian_product(*vectors):
    return list(product(*vectors))

# Example vectors
vector1 = [1, 2, 3]
vector2 = ['a', 'b']
vector3 = [True, False]

# Compute the Cartesian product
result = cartesian_product(vector1, vector2, vector3)

# Print the result
print(result)

In [ ]:
# 91. How to create a record array from a regular array?

# Regular array
regular_array = np.array([(1, 'John', 25), (2, 'Alice', 30), (3, 'Bob', 35)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])

# Convert to record array
record_array = np.rec.array(regular_array)

# Print the record array
print(record_array)

In [8]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

# Generate a large vector Z
Z = np.random.rand(1000000)

# Method 1: Using NumPy's power function
result1 = np.power(Z, 3)

# Method 2: Using the ** operator
result2 = Z ** 3

# Method 3: Using a loop
result3 = np.empty_like(Z)
for i in range(len(Z)):
    result3[i] = Z[i] ** 3

In [ ]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

# Create arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [2, 3, 1],
              [5, 6, 4],
              [8, 9, 7],
              [3, 1, 2],
              [6, 4, 5]])

B = np.array([[1, 2],
              [4, 5]])

# Convert arrays to sets of tuples for easier comparison
A_set = set(map(tuple, A))
B_set = set(map(tuple, B))

# Find rows of A that contain elements of each row of B
result_rows = [idx for idx, row in enumerate(A_set) if B_set.intersection(set(row)) == B_set]

# Get the corresponding rows of A
result = A[result_rows]

print("Rows of A that contain elements of each row of B regardless of order:")
print(result)

In [10]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

# Create a 10x3 matrix
matrix = np.random.randint(0, 3, size=(10, 3))

# Extract rows with unequal values
unequal_rows = matrix[np.apply_along_axis(lambda x: len(np.unique(x)) > 1, axis=1, arr=matrix)]

print("Matrix:")
print(matrix)
print("\nRows with unequal values:")
print(unequal_rows)

Matrix:
[[1 1 0]
 [1 0 0]
 [2 2 0]
 [0 2 1]
 [2 0 1]
 [1 2 0]
 [0 0 1]
 [2 0 2]
 [2 0 1]
 [2 0 2]]

Rows with unequal values:
[[1 1 0]
 [1 0 0]
 [2 2 0]
 [0 2 1]
 [2 0 1]
 [1 2 0]
 [0 0 1]
 [2 0 2]
 [2 0 1]
 [2 0 2]]


In [ ]:
# 95. Convert a vector of ints into a matrix binary representation

# Example vector of integers
vector = np.array([1, 2, 3, 4])

# Convert integers to their binary representation
binary_matrix = np.unpackbits(vector[:, np.newaxis], axis=1)

print("Binary matrix representation:")
print(binary_matrix)

In [ ]:
# 96. Given a two dimensional array, how to extract unique rows?

# Example 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [1, 2, 3],
                     [7, 8, 9],
                     [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array_2d, axis=0)

print("Original 2D array:")
print(array_2d)
print("\nUnique rows:")
print(unique_rows)

In [ ]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#Inner product (dot product):
#Einsum equivalent: np.einsum('i,i->', A, B)
#This computes the dot product of vectors A and B.

#Outer product:
#Einsum equivalent: np.einsum('i,j->ij', A, B)
#This computes the outer product of vectors A and B, resulting in a matrix.

#Sum:
#Einsum equivalent: np.einsum('i->', A)
#This computes the sum of all elements in vector A.

#Element-wise multiplication:
#Einsum equivalent: np.einsum('i,i->i', A, B)
#This computes the element-wise multiplication of vectors A and B, resulting in a new vector with the same length as the input vectors.

In [ ]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

def equidistant_samples(X, Y, num_samples):
    # Calculate the total length of the path
    distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
    total_length = np.sum(distances)

    # Calculate the distance between samples
    sample_distance = total_length / (num_samples - 1)

    # Interpolate points along the path at regular intervals
    samples = []
    cumulative_distance = 0
    for i in range(len(X) - 1):
      segment_length = np.sqrt((X[i+1] - X[i])**2 + (Y[i+1] - Y[i])**2)
      if cumulative_distance + segment_length >= sample_distance:
            remaining_distance = sample_distance - cumulative_distance
            ratio = remaining_distance / segment_length
            sample_x = X[i] + ratio * (X[i+1] - X[i])
            sample_y = Y[i] + ratio * (Y[i+1] - Y[i])
            samples.append((sample_x, sample_y))
            X = X[i+1:]
            Y = Y[i+1:]
            cumulative_distance = segment_length - remaining_distance
        else:
            cumulative_distance += segment_length

    return np.array(samples)

# Example usage:
# Define two vectors X and Y describing the path
X = np.array([0, 1, 3, 6, 10])
Y = np.array([0, 2, 5, 3, 1])

# Number of equidistant samples
num_samples = 10

# Get equidistant samples along the path
samples = equidistant_samples(X, Y, num_samples)
print("Equidistant samples along the path:")
print(samples)

In [ ]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

def select_multinomial_rows(X, n):
    # Check if each element in X is an integer
    is_integer = np.equal(X, np.round(X))

    # Check if the sum of each row in X is equal to n
    row_sum_equals_n = np.sum(X, axis=1) == n

    # Select rows that contain only integers and sum to n
    selected_rows = X[np.all(is_integer, axis=1) & row_sum_equals_n]

    return selected_rows

# Example usage:
# Define the integer n and the 2D array X
n = 10
X = np.array([[1, 2, 3, 4],
              [0.5, 0.5, 9, 0],
              [3, 5, 2, 0],
              [10, 0, 0, 0]])

# Select rows from X that can be interpreted as draws from a multinomial distribution with n degrees
selected_rows = select_multinomial_rows(X, n)
print("Rows from X that meet the criteria:")
print(selected_rows)

In [16]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

def bootstrap_confidence_interval(X, num_samples, alpha=0.05):
    means = []
    for _ in range(num_samples):
        resampled_X = np.random.choice(X, size=len(X), replace=True)
        resampled_mean = np.mean(resampled_X)
        means.append(resampled_mean)

    # Compute percentiles
    lower_percentile = 100 * alpha / 2
    upper_percentile = 100 * (1 - alpha / 2)
    lower_bound = np.percentile(means, lower_percentile)
    upper_bound = np.percentile(means, upper_percentile)

    return lower_bound, upper_bound

# Example usage
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Example 1D array
num_samples = 1000  # Number of bootstrap samples
alpha = 0.05  # Significance level for a 95% confidence interval

lower_bound, upper_bound = bootstrap_confidence_interval(X, num_samples, alpha)
print("Bootstrapped 95% Confidence Interval for the mean:", (lower_bound, upper_bound))


Bootstrapped 95% Confidence Interval for the mean: (3.7, 7.3)
